apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-driver-deployment
  namespace: go-driver
spec:
  # TODO(lwsanty): autoscaling
  replicas: 5
  selector:
    matchLabels:
      app: go-driver-app
  template:
    metadata:
      namespace: go-driver
      labels:
        app: go-driver-app
    spec:
      containers:
        - name: go-driver-server
          image: bblfsh/go-driver:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
          ports:
            - name: grpc
              containerPort: 9432
          env:
            - name: LOG_LEVEL
              value: debug
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
